### ISSUE TITLE
Errors on ipv6 disabled systems.

### ISSUE THREAD

**Issue by cjbidwell** [ansible-lockdown/RHEL8-STIG#26] opened 2021-05-19 18:49 UTC
Reference:  RHEL-08-040210, RHEL-08-040230, RHEL-08-040240, RHEL-08-040250, RHEL-08-040260, RHEL-08-040261, RHEL-08-040262, RHEL-08-040280 all fail when trying to apply when ipv6 is disabled.  I've added ignore_errors to each of these blocks.  Perhaps I missed a variable where ipv6 is disabled in the playbook where it would exclude these checks.

**Comment by georgenalen** [comment] 2021-05-20 17:11
@cjbidwell,
 Thanks for raising the issue, I am having some trouble reproducing it so I'm hoping you can send along some more information. I have run the role in both cent8/RHEL8 with IPv6 disabled and the role ran without issue. 

1) What version of Ansible/Tower are you running? 

2) What version of python are you running on the Ansible/Tower server? 

3) How did you disable IPv6? 

4) What is the error you are getting on those controls when they fail? 


George

**Comment by cjbidwell** [comment] 2021-05-20 21:18
`ansible 2.9.20
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/chris.bidwell/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]`

I disabled ipv6 by adding this to /etc/default/grub.conf:
GRUB_CMDLINE_LINUX="crashkernel=auto resume=/dev/mapper/vg_rhel-lv.swap rd.lvm.lv=vg_rhel/lv.root rd.lvm.lv=vg_rhel/lv.swap rd.lvm.lv=vg_rhel/lv.usr **ipv6.disable=1** net.ifnames=0 rhgb quiet fips=1 boot=UUID=812e1559-ded1-4585-9200-7b7080c2c47f page_poison=1 vsyscall=none slub_debug=P audit=1 audit_backlog_limit=8192 pti=on"

After running the pb again, it looks like I get the error for both ipv4 and ipv6.  This is the error I'm getting:
`ok: [rhel8-base-lx] => (item=net.ipv4.conf.default.accept_redirects)
failed: [rhel8-base-lx] (item=net.ipv6.conf.default.accept_redirects) => {"ansible_loop_var": "item", "changed": false, "item": "net.ipv6.conf.default.accept_redirects", "msg": "Failed to reload sysctl: kernel.kexec_load_disabled = 1\nfs.protected_symlinks = 1\nfs.protected_hardlinks = 1\nkernel.randomize_va_space = 2\nkernel.core_pattern = |/bin/false\nnet.ipv4.conf.default.accept_redirects = 0\nnet.ipv4.conf.all.send_redirects = 0\nnet.ipv4.icmp_echo_ignore_broadcasts = 1\nnet.ipv4.conf.all.accept_source_route = 0\nnet.ipv4.conf.default.accept_source_route = 0\nnet.ipv4.ip_forward = 0\nnet.ipv4.conf.default.send_redirects = 0\nnet.ipv4.conf.all.accept_redirects = 0\nkernel.unprivileged_bpf_disabled = 1\nkernel.yama.ptrace_scope = 1\nkernel.kptr_restrict = 1\nuser.max_user_namespaces = 0\nnet.ipv4.conf.all.rp_filter = 1\nkernel.dmesg_restrict = 1\nkernel.perf_event_paranoid = 2\nkernel.kexec_load_disabled = 1\nfs.protected_symlinks = 1\nfs.protected_hardlinks = 1\nkernel.core_pattern = |/bin/false\nsysctl: cannot stat /proc/sys/net/ipv6/conf/default/accept_redirects: No such file or directory\nsysctl: cannot stat /proc/sys/net/ipv6/conf/all/accept_source_route: No such file or directory\nsysctl: cannot stat /proc/sys/net/ipv6/conf/default/accept_source_route: No such file or directory\nsysctl: cannot stat /proc/sys/net/ipv6/conf/all/forwarding: No such file or directory\nsysctl: cannot stat /proc/sys/net/ipv6/conf/all/accept_ra: No such file or directory\nsysctl: cannot stat /proc/sys/net/ipv6/conf/default/accept_ra: No such file or directory\nsysctl: cannot stat /proc/sys/net/ipv6/conf/all/accept_redirects: No such file or directory\n"}`

**Comment by georgenalen** [comment] 2021-05-21 13:25
@cjbidwell,
 Thanks for sending that along, I am able to reproduce it disabling via grub. There are three ways to disable ipv6 and GRUB won't create those files/symlinks which is why they are failing. I'll sort through this and get a fix merged through. Thanks again. 

George

**Comment by cjbidwell** [comment] 2021-05-21 19:29
Thanks!  I appreciated you checking into it.  I had a feeling it was because of the grub setup of it.  Lemme do a new kickstart install not using the grub and I'll write a playbook to disable ipv6 through that.  If you're not getting a lot of other requests via this route, I'd just let it lie.

**Comment by georgenalen** [comment] 2021-05-25 17:29
As a heads up there are a couple ways to address the issue you are seeing and setting the task to ignore errors is one of them. I'm not a fan of that just because I'm not a fan of straight up ignoring errors since that would ignore other errors too. My implementation will just be to have sysctl not reload in this scenario. I'm still mulling to just command/shell it out instead of using the module, but if things are OK with the module I'm going that route. The setting is still set and useful even without the reload (from what I've read so far...). 

George

**Comment by georgenalen** [comment] 2021-08-24 12:09
This issue was resolved with the latest release

**Closed by georgenalen** 2021-08-24 12:09 UTC
Labels: bug
